#!/usr/bin/env dash

MAIN_DIR="/home/simrat39/0-icon-pack"

FOLDER1="$MAIN_DIR/app/src/main/res/drawable-xxxhdpi"
FOLDER2="$MAIN_DIR/app/src/main/res/drawable-xxhdpi"
FOLDER3="$MAIN_DIR/app/src/main/res/drawable-xhdpi"
FOLDER4="$MAIN_DIR/app/src/main/res/drawable-mdpi"
FOLDER5="$MAIN_DIR/app/src/main/res/drawable-hdpi"

FOLDER6="$MAIN_DIR/app/src/main/res/mipmap-xxxhdpi"
FOLDER7="$MAIN_DIR/app/src/main/res/mipmap-xxhdpi"
FOLDER8="$MAIN_DIR/app/src/main/res/mipmap-xhdpi"
FOLDER9="$MAIN_DIR/app/src/main/res/mipmap-mdpi"
FOLDER10="$MAIN_DIR/app/src/main/res/mipmap-hdpi"

FOLDER11="$MAIN_DIR/app/src/main/res/drawable-anydpi-v26"

read -p "Enter image name : " image

cp ${FOLDER1}/${image}.png ${FOLDER2}
cp ${FOLDER1}/${image}.png ${FOLDER3}
cp ${FOLDER1}/${image}.png ${FOLDER4}
cp ${FOLDER1}/${image}.png ${FOLDER5}

if [ "$1" = "adapt" ]
    then
    cp ${FOLDER6}/${image}_foreground.png ${FOLDER7}
    cp ${FOLDER6}/${image}_background.png ${FOLDER7}

    cp ${FOLDER6}/${image}_foreground.png ${FOLDER8}
    cp ${FOLDER6}/${image}_background.png ${FOLDER8}

    cp ${FOLDER6}/${image}_foreground.png ${FOLDER9}
    cp ${FOLDER6}/${image}_background.png ${FOLDER9}

    cp ${FOLDER6}/${image}_foreground.png ${FOLDER10}
    cp ${FOLDER6}/${image}_background.png ${FOLDER10}

    cp -r ${FOLDER11}/reddit.xml ${FOLDER11}/${image}.xml
    sed -i "s/reddit/$image/g" "${FOLDER11}/${image}.xml"

    find ${FOLDER7} -iname ${image}_foreground.png -exec convert \{} -verbose -resize 324x324\> \{} \;
    find ${FOLDER8} -iname ${image}_foreground.png -exec convert \{} -verbose -resize 216x216\> \{} \;
    find ${FOLDER9} -iname ${image}_foreground.png -exec convert \{} -verbose -resize 162x162\> \{} \;
    find ${FOLDER10} -iname ${image}_foreground.png -exec convert \{} -verbose -resize 108x108\> \{} \;

    find ${FOLDER7} -iname ${image}_background.png -exec convert \{} -verbose -resize 324x324\> \{} \;
    find ${FOLDER8} -iname ${image}_background.png -exec convert \{} -verbose -resize 216x216\> \{} \;
    find ${FOLDER9} -iname ${image}_background.png -exec convert \{} -verbose -resize 162x162\> \{} \;
    find ${FOLDER10} -iname ${image}_background.png -exec convert \{} -verbose -resize 108x108\> \{} \;
fi

find ${FOLDER1} -iname ${image}.png -exec convert \{} -verbose -resize 192x192\> \{} \;
find ${FOLDER2} -iname ${image}.png -exec convert \{} -verbose -resize 144x144\> \{} \;
find ${FOLDER3} -iname ${image}.png -exec convert \{} -verbose -resize 96x96\> \{} \;
find ${FOLDER4} -iname ${image}.png -exec convert \{} -verbose -resize 72x72\> \{} \;
find ${FOLDER5} -iname ${image}.png -exec convert \{} -verbose -resize 48x48\> \{} \;

./gradlew installDebug
