#!/usr/bin/env dash

set -x

killall lemonbar a.out

BAR_HEIGHT_RATIO=04

#I3_GAP=$(grep -P "gaps\souter\s[0-9]+" ~/.config/i3/config | sed 's/\w*\s//g')

# Find bspwm gap ratio
BSPWM_GAP=$(awk '/window_gap/{print $4}' $HOME/.config/bspwm/bspwmrc)
if [ $(echo $BSPWM | wc -l) -gt 1 ]; then BSPWM_GAP=0$BSPWM_GAP; fi

MONITOR_WIDTH=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 1p)
MONITOR_HEIGHT=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 2p)
BAR_WIDTH=$(expr $MONITOR_WIDTH - $((BSPWM_GAP * 2)))
BAR_HEIGHT=$(echo "$MONITOR_HEIGHT * .$BAR_HEIGHT_RATIO" | bc -l | sed 's/\..*//')

# Always compile
cd ~/cxxbar

./a.out | lemonbar \
            -o -1 \
            -f 'fixed:pixelsize=12;1' \
            -o -3 \
            -f 'Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid:size=8' \
            -f 'FiraCode Nerd Font:style=Retina:size=12' \
            -g "$BAR_WIDTH"x"$BAR_HEIGHT"+"$BSPWM_GAP"+"$((BSPWM_GAP / 2))" \
            -B '#1E1F29' \
            -F "#ffffff" \
            -U "#ffffff" \
            -b \
            -u 2 \
            -p | dash
