#!/bin/bash

NODE_CURRENT=$(bspc query -N -n focused)
$@ &
WATCH=$(bspc subscribe -c 1 node_add)
NODE_NEW=${WATCH##* }
bspc node -s $NODE_CURRENT
bspc node $NODE_CURRENT --flag hidden=on
while read EVENT
do
  [ "${EVENT##* }" = "$NODE_NEW" ] && break
done < <(bspc subscribe node_remove)
bspc node $NODE_CURRENT --flag hidden=off
bspc node $NODE_CURRENT --focus
