#!/bin/dash

STATUS=$(amixer get Master | egrep -o -m1 '(\[on\]|\[off\])')
VOLUME=$(amixer get Master | egrep -o -m1 '[0-9]*%')

if test "${1}" = "--status";
then
  if test "$STATUS" = "[on]";
  then
    echo "  $VOLUME";
  elif test "$STATUS" = "[off]";
  then
    echo "";
  fi
elif test "${1}" = "--volupdate";
then
  amixer -d sset Master ${2}
fi
