#!/bin/dash
if test "${1}" = "--status";
then
    STATUS=$(pacmd list-sinks | awk '/muted/ { print $2 }')
    VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

    if test "$STATUS" = "no";
    then
        echo "  $VOLUME";
    elif test "$STATUS" = "yes";
    then
        echo "";
    fi
elif test "${1}" = "--volupdate";
then
  pactl set-sink-volume @DEFAULT_SINK@ "${2}"
fi
