#!/bin/sh

pkill sxhkd
pkill picom

sxhkd &

. ~/.bin/lemonbar_wrapper &

xset b off

# intellij sheit
wmname LG3D 

feh --bg-scale ~/.config/walls/wall.png &

picom --config ~/.config/picom/picom.conf &

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7
bspc monitor eDP-1-1 -d 8 9 10

# bspc monitor eDP-1 -d 1 2 3 4 5 6 7

bspc config border_width 0
bspc config window_gap 5
bspc config bottom_padding 40
