#! /bin/sh

pkill sxhkd
pkill compton

sxhkd &

xset b off &

. ~/.config/dunst/launch.sh &

. ~/.bin/lemonbar_wrapper &

# intellij sheit
wmname LG3D

feh --bg-scale ~/.config/walls/wallhaven-nib.jpg &

compton --config ~/.config/picom/picom.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

bspc config border_width         0 &
bspc config window_gap          20 &

bspc config split_ratio         0.5 &
bspc config border_radius 	7 &
