require("general")
require("mappings")
require("plugins")
require("statusline")
require("globals")

require("config/bufferline")
require("config/compe")
require("config/dashboard-nvim")
require("config/flutter-tools")
require("config/gitsigns")
require("config/indent-blankline")
require("config/lspconfig")
require("config/nvim-autopairs")
require("config/nvim-colorizer")
require("config/nvim-dap-ui")
require("config/nvim-tree")
require("config/nvim-ts-autotag")
require("config/rust-tools")
require("config/symbols-outline")
require("config/telescope")
require("config/tree-sitter")

require("lspui").setup()

vim.cmd("colorscheme dracula")
-- vim.opt.guifont='FiraCodeNerdFont'
